language: rust
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
    - stable
    - beta
install:
    - pip install --user codecov
    - export PATH=$HOME/.local/bin:$PATH:$HOME/local/bin:$HOME/.cargo/bin
    - export CC=gcc-4.9
    - export CXX=g++-4.9
    # Build and cache kcov
    - |
      if [ -f $HOME/local/bin/kcov ]; then
          echo "Using cached kcov from ~/local/bin/kcov"
      else
          mkdir -p $HOME/local
          cd $HOME/local
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
          make install
          cd $TRAVIS_BUILD_DIR
      fi
    # Build and cache mdbook
    - |
      if [ -f $HOME/.cargo/bin/mdbook ]; then
          echo "Using cached mdbook from ~/.cargo/bin/mdbook"
      else
          cargo install mdbook
      fi
script:
    # Run unit tests and doc tests in debug mode
    - cargo test --lib
    - cargo test --doc
    # Run all tests in release mode
    - cargo test --release
after_script:
    - |
      if [[ "${TRAVIS_RUST_VERSION}" == "stable" && "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
          kcov --include-pattern=$(pwd) target/kcov target/debug/cymbalum-*
          codecov --file target/kcov/cymbalum-*/cobertura.xml
          git clone https://${GH_TOKEN}@github.com/Luthaf/cymbalum.git target/website
          ./doc/publish.sh
      fi
cache:
  directories:
      - $HOME/local/bin
      - $HOME/.cargo/bin
env:
  global:
    secure: DlziexmlR66bR+pIXN/qUlMfnANY6sRSP6ZDKmLKyzLQghCShoL6TF5s+GEN7uB39U4IT9/706MrvCUPD7azobrJTX/mQsKraSPwlQ3uBlPtiVy6sLSK51jfBsucuiFibMiwv9FGv0DB687qnpDW1Wo2x1UkdcxsILlpThxCNlHWuQCficgI/LAegXoyvxfNfrcEeXhAQhPuUILMEODfbPuLwwynclQHN+JiMIhjVfU/rVffdJPflvxMBz0M9YaJKHgYvffDxIRVcZRYjzzMMyhbrFlLbTWOqfie2jppKqqZ7LhnT+ycqXPGowif5mt5yNWIEI7xYL4k11LgsVLbCg2x3OGUTjqhV39QKl49/rClH1K63I8CqF3KjOZXJ1iMhbkUoZ5OlyTA7OT7K0JN/+ha7bmoQuE6OkJ6cVhJH0IchJtprius9z+z6uVIlF5weotZ0uiAJjDggRqz5PEvVIIwaVmEnhVj0NfOIxd73ct31HnJkT7Ye5jOSmA+8NOuXyNQOXQZPhi4KQmpBIpe7ett5XMGJZXv8Guk3kEygJr2hEldB9KxXWuEoQ2wPTtfVvAXsW1CIxso+FqvMuehLMJjgJUJRuPyvPFYKfF/wLPc7p2csLlJj2S6NXp4DdZt7i2dAZDCDFp3pkhdvULBmGrGQZC6wCDYijNQ0mJiimw=
