[package]
name = "cymbalum"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://luthaf.github.io/cymbalum"
repository = "https://github.com/Luthaf/cymbalum"
readme = "README.md"
license = "BSD"

[lib]
name = "cymbalum"
doctest = false

[dependencies]
chemfiles = "0.5.2"
rand = "0.3.14"
log = "0.3.5"
yaml-rust = "0.3.0"
special = "0.5.1"
bitflags = "0.4.0"
ndarray = "0.4.0"

[dependencies.num]
version = "0.1.31"
# We only need the One and Zero traits
default-features = false

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy/"
optional = true

[features]
default = []
lint = ["clippy"]

[profile.release]
debug = true
