[package]
name = "cymbalum"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://luthaf.github.io/cymbalum"
repository = "https://github.com/Luthaf/cymbalum"
readme = "README.md"
license = "BSD"

[lib]
name = "cymbalum"
doctest = false

[dependencies]
chemfiles = "0.5.4"
rand = "0.3.14"
log = "0.3.5"
toml = "0.1.28"
special = "0.5.1"
bitflags = "0.4.0"
ndarray = "0.4.0"
lazy_static = "0.1.15"
num-traits = "0.1.32"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy/"
optional = true

[dependencies.herbie-lint]
git = "https://github.com/mcarton/rust-herbie-lint/"
optional = true

[dev-dependencies]
tempfile = "2.1.1"

[features]
default = []
lint = ["clippy", "herbie-lint"]

[profile.release]
debug = true
