[package]
name = "cymbalum"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://luthaf.github.io/cymbalum"
repository = "https://github.com/Luthaf/cymbalum"
readme = "README.md"
license = "BSD"

[lib]
name = "cymbalum"
doctest = false

[dependencies]
chemfiles = "0.5.5"
rand = "0.3.14"
log = "0.3.5"
toml = "0.1.28"
special = "0.7.0"
bitflags = "0.7.0"
ndarray = "0.6.0"
lazy_static = "0.2.0"
num-traits = "0.1.32"

[dev-dependencies]
tempfile = "2.1.1"

[profile.release]
debug = true

