[package]
name = "lumol"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://luthaf.github.io/cymbalum"
repository = "https://github.com/Luthaf/cymbalum"
readme = "README.md"
license = "BSD"

[lib]
name = "lumol"

[dependencies]
chemfiles = "0.6"
rand = "0.3"
log = "0.3"
toml = "0.1"
special = "0.7"
bitflags = "0.7"
ndarray = "0.6"
lazy_static = "0.2"
num-traits = "0.1"

[dev-dependencies]
tempfile = "2.1"

[profile.release]
debug = true
